apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: java-webapp-run
  namespace: {{NAMESPACE}}        # <-- your student’s project
spec:
  pipelineRef:
    name: java-webapp-pipeline-optimized
  params:
    - name: git-url
      value: {{GIT_REPO_URL}}
    - name: git-revision
      value: main
    - name: build-name
      value: java-webapp-build-beta   # matches your Shipwright Build metadata.name
    - name: namespace
      value: {{NAMESPACE}}           # target for both Shipwright and deploy
  workspaces:
    - name: source
      persistentVolumeClaim:
        claimName: shared-pvc   # or whatever your PVC is named
