apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: java-webapp-{{NAMESPACE}}
  namespace: openshift-gitops
  labels:
    app: java-webapp
    student: {{NAMESPACE}}
  annotations:
    # ArgoCD Image Updater configuration
    argocd-image-updater.argoproj.io/image-list: webapp=image-registry.openshift-image-registry.svc:5000/{{NAMESPACE}}/java-webapp:latest
    argocd-image-updater.argoproj.io/webapp.update-strategy: latest
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/git-branch: {{NAMESPACE}}
    argocd-image-updater.argoproj.io/git-repository: {{GIT_REPO_URL}}
spec:
  project: default
  source:
    repoURL: {{GIT_REPO_URL}}
    targetRevision: {{NAMESPACE}}  # student branch name matches namespace
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: {{NAMESPACE}}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false  # namespace should already exist
      - PrunePropagationPolicy=foreground
      - PruneLast=true
  revisionHistoryLimit: 10
